<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = [
        'author_id', 'article_id', 'comment'
    ];

    public function author()
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::updating(function (Comment $comment) {
            $after = $comment->getDirty();
            $comment->histories()->attach(auth()->id(), [
                'before' => json_encode(Arr::only($comment->fresh()->toArray(), array_keys($after))),
                'after' => json_encode($after)
            ]);
        });

    }

    public function article()
    {
        return $this->belongsTo(Article::class);
    }

    public function histories()
    {
        return $this->belongsToMany(User::class, 'comment_histories')
            ->withPivot(['before', 'after'])->withTimestamps();
    }
}
